# Generated by Django 5.1.5 on 2025-01-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0003_about"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutMe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=155, verbose_name="Ключ")),
                ("value", models.CharField(max_length=155, verbose_name="Значение")),
            ],
            options={
                "verbose_name_plural": "Об мне",
            },
        ),
    ]
