# Generated by Django 5.1.5 on 2025-01-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0004_aboutme"),
    ]

    operations = [
        migrations.CreateModel(
            name="Works",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Описание")),
                ("image", models.ImageField(upload_to="works", verbose_name="Фото")),
            ],
            options={
                "verbose_name_plural": "Работы",
            },
        ),
    ]
