# Generated by Django 4.2.7 on 2025-01-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0006_works_description2_works_image_2_works_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=155, verbose_name="Имя")),
                ("email", models.EmailField(max_length=254, verbose_name="Почта")),
                ("phone", models.IntegerField(verbose_name="Номер телефона")),
                ("subject", models.CharField(max_length=155, verbose_name="Обект")),
                ("message", models.TextField(verbose_name="Сообщение")),
            ],
        ),
    ]
